config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :projects
      resources :users

      root to: "projects#index"
    end
  devise_for :users

  resources :projects
  get 'home/about'
  root 'home#index'

  devise_scope :user do
    get '/users/sign_out', to:'devise/sessions#destroy'
  end

end
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
# Defines the root path route ("/")
# root "articles#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
        belongs_to :user

        validates :project_title, presence: true

        validates :project_description, presence: true  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :Projects

  def admin?
    admin
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin
    # before_action :authenticate_user!

    def authenticate_admin
      if !current_user
        flash[:alert] = "You don't have permission to access the admin dashboard."
        redirect_to root_path
      elsif !current_user.admin
        flash[:alert] = "You don't have permission to access the admin dashboard."
        redirect_to root_path
      end
    end
    
  end
end


      # if user_signed_in? && !current_user.admin
      #   flash[:alert] = "You don't have permission to access the admin dashboard."
      #   redirect_to root_path
      # end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end 

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    # @project = Project.new
    @project = current_user.Projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    # @project = Project.new(project_params)
    @project = current_user.Projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        @project.errors.delete(:project_title)
        @project.errors.delete(:project_description)
        flash.now[:notice] = "Project title or description cannot be blank."
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @project = current_user.Projects.find_by(id: params[:id])
    redirect_to projects_path, notice: "Not Authorized To perform that function" if @project.nil?

  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:project_title, :project_description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to(image_tag("mainlogo.png"), root_path) %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">


      </ul>

      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

      <ul class="navbar-nav me-auto mb-2 mb-lg-0 "  >

        <li class="nav-item dropdown" id = "mynavitem">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" >
            Actions
          </a>

          <ul class="dropdown-menu"> 
            <% if user_signed_in?%>
              <li><%= link_to 'Edit profile', edit_user_registration_path, class: "dropdown-item"%></li>

              <li><%= link_to 'Create project', new_project_path, class: "dropdown-item"%></li>

              <li><hr class="dropdown-divider"></li>
            
              <li >
                <%= link_to 'View Projects', projects_path, class: "dropdown-item" %>
              </li>
            <%else%>
              <li >
                <%= link_to 'View about page', home_about_path, class: "dropdown-item" %>
              </li>
            <%end%>

          </ul>
        </li>

      </ul>
      <% if user_signed_in?%>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
            <li class = "nav-item">
              <%= link_to "Sign Out", destroy_user_session_path, class:"nav-link"%>
            </li>
          </ul>


          <% if current_user.admin%>
            <%= link_to 'Admin Profile', admin_projects_path, class: 'btn btn-info' %><br><br>
          <%end%>

        <% else %>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 "  >

            <li class = "nav-item">
              <%= link_to "Sign In", new_user_session_path, class:"nav-link"%>
            </li>

            <li class = "nav-item">
              <%= link_to "Sign UP", new_user_registration_path, class:"btn btn-dark"%>
            </li>

          </ul>
      <% end%>

    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class = "separtionDiv"></div>

<div class="container-sm">
  <div class="row align-items-center">

    <div class="col-2">

    </div>

    <div class="col">

        <h1>About page</h1>
        <br><br>
        <h5>
        note
        </h5>

        <h5>
        * The basccamp icon takes you back to the home page anytime it is clicked
        </h5>
        <br><br>
        <h5>
        * sigh up or sign in to view more pages in the action dropdown buttom
        </h5> 
        <h5>
        * read my README file for more details.
        </h5>
        <br><br>   
    </div>

    <div class="col-2">

    </div>

  </div>
</div>
 

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <div class = "separtionDiv"></div>

    <div class="container-sm">
        <div class="row align-items-center">
            <div class="col">
                <%= image_tag "BasecampLogo.PNG" %>
            </div>

            <div class="col">
                <div class = "welcomediv">
                    <h1>Welcome!</h1>
                </div>

            </div>
        </div>
    </div>

    <div class = "separtionDiv"></div>

    <div class="container-sm">
        <div class="row align-items-center">
            <div class="col">
            <%= link_to image_tag("BCPerson1.PNG", class: "img1") %>
            </div>

            <div class="col">
            <%= link_to image_tag("BCPerson2.PNG", class: "img2") %>
            </div>
        </div>
    </div>


    <div class="centercontent">
        <h1 class = "footertext">Try now!</h1>
        <h1 class = "footertext">&</h1>
        <div class = "footerdiv">
            <h3 class = "footertext">progress on more projects than you ever thought possible.</h3>
      </div>
    </div>
</body>
</html>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice%>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBasecamp1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag 'BC1css.css' %>
  </head>

  <body>
  
    <%= render 'home/navbar'%>
    
    <br>
    <% if notice %>
      <%= render 'layouts/alerts'%>
    <% end %>

    <%= yield %>
  

  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div>
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class = "text", id = "projectdiv">
    <div>
      <%= form.label :project_title %>
      <%= form.text_field :project_title, class: "form-control", placeholder: "enter project title here"  %>
    </div>

    <div>
      <%= form.label :project_description%>
      <%= form.text_area :project_description, class: "form-control", placeholder: "enter project description here" %>
    </div>

    <div>
      <%= form.number_field :user_id, id: :project_user_id, class:  "form-control", value: current_user.id, type: :hidden  %>
    </div>

  </div>

  <div>

    <%= form.submit class: "btn btn-dark" %>

  </div>
<% end %>

app/views/projects/_project.html.erb
<div  id="<%= dom_id project %>">

  <div id = "projectdiv" >
    <span class = "text">
      <p>
        <strong >Project title:</strong>

        "<%= project.project_title%>"

      </p>
        <hr>
      <p>
        <strong >Project description:</strong>
        <%= project.project_description %>
      </p>
        <hr>
      <p>
        <strong >User ID:</strong>
        <%= project.user_id%>
      </p>
    </span>
  </div>

</div>

app/views/projects/edit.html.erb
		

<div class = "separtionDiv"></div>

<div class="container-sm">
    <div class="row align-items-center">



        <div class="col">
		
            <h1>Editing project</h1>

            <%= render "form", project: @project %>

            <br>
            <div>
                <%= link_to "Show this project", @project, class: "btn btn-outline-primary" %> |
                <%= link_to "Back to projects", projects_path, class: "btn btn-outline-secondary" %>
            </div>
        </div>


        <div class="col">

        </div>

    </div>
</div>
 

app/views/projects/index.html.erb
<div class = "separtionDiv"></div>

<div class="container-sm">
  <div class="row align-items-center">

    <div class="col-2">
      <div class = "">
        <h1>
          
        </h1>
      </div>

    </div>

    <div class="col">
        <h1>Projects</h1>

        <div id="projects">
          <% @projects.each do |project| %>
            <% if project.user == current_user%>

              <%= render project %>
              <p>
                <%= link_to "Show this project", project, class: "btn btn-outline-primary" %>
             </p>
            
            <%end%>
          <% end %>
        </div>

        <%= link_to "New project", new_project_path, class: "btn btn-primary" %>

    </div>

    <div class="col">
      <h1>
        
      </h1>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container-sm">
      <div class="row align-items-center">

        <div class="col">
          <h1>New project</h1>

          <%= render "form", project: @project %>

          <br>

          <div>
            <%= link_to "Back to projects", projects_path, class: "btn btn-outline-secondary" %>
          </div>
          
        </div>

        <div class = "col">

        </div>
      </div>
</div>

app/views/projects/show.html.erb
<div class = "separtionDiv"></div>

<div class="container-sm">
  <div class="row align-items-center">

  <div class="col">

      
    <%= render @project %>

    <div>
      <div>
      <br>
        <%= link_to "Edit this project", edit_project_path(@project), class: "btn btn-outline-secondary" %> |
        <%= link_to "Back to projects", projects_path, class: "btn btn-outline-secondary" %>
      </div>
      <div>
      <br>
        <%= button_to "Delete project", @project, method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>

  <div class="col">

  </div>
  </div>
</div>
 